[project]
name = "smolagents-with-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "litellm>=1.65.4.post1",
    "mcp[cli]>=1.6.0",
    "ruff>=0.11.4",
    "smolagents[mcp]>=1.13.0",
    "typer>=0.15.2",
]
